=== web-infra-dev/rspack/crates/rspack_test_utils/test.config.scheme.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TestConfig",
  "description": "The configuration is used to configure the test in Rust. The structure should be closed to the webpack configuration.",
  "type": "object",
  "properties": {
    "builtins": {
      "$ref": "#/definitions/Builtins"
    },
    "debug": {
      "$ref": "#/definitions/Debug"
    },
    "entry": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/EntryItem"
      }
    },
    "module": {
      "$ref": "#/definitions/Module"
    },
    "output": {
      "$ref": "#/definitions/Output"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "Builtins": {
      "type": "object",
      "properties": {
        "define": {
          "default": {},
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "Debug": {
      "type": "object",
      "properties": {
        "sideEffects": {
          "default": false,
          "type": "boolean"
        },
        "treeshake": {
          "default": false,
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "EntryItem": {
      "type": "object",
      "required": [
        "import"
      ],
      "properties": {
        "import": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "runtime": {
          "default": "runtime",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "additionalProperties": false
    },
    "Module": {
      "type": "object",
      "properties": {
        "rules": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Rule"
          }
        }
      },
      "additionalProperties": false
    },
    "ModuleRule": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "matcher",
            "type"
          ],
          "properties": {
            "matcher": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "regexp"
              ]
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "Output": {
      "type": "object",
      "properties": {
        "chunkFilename": {
          "default": "[name][ext]",
          "type": "string"
        },
        "cssChunkFilename": {
          "default": "[name][ext]",
          "type": "string"
        },
        "cssFilename": {
          "default": "[name][ext]",
          "type": "string"
        },
        "filename": {
          "default": "[name][ext]",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "Rule": {
      "type": "object",
      "properties": {
        "sideEffect": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "test": {
          "anyOf": [
            {
              "$ref": "#/definitions/ModuleRule"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== web-infra-dev/rspack/crates/rspack/tests/tree-shaking/module-rule-side-effects1/test.config.json
{
    "entry": {
        "main": {
            "import": [
                "./index.js"
            ]
        }
    },
    "builtins": {
        "define": {
            "process.env.NODE_ENV": "'development'"
        }
    },
    "debug": {
        "treeshake": true,
        "sideEffects": true
    },
    "module": {
        "rules": [
            {
                "test": {
                    "type": "regexp",
                    "matcher": "b.js$"
                },
                "sideEffect": false
            }
        ]
    }
}
